config/routes.rb
SoftwareProject::Application.routes.draw do
  
  get "game/index"

  get "game/new"

  get "game/create"

  root :to            => 'pages#index'
  match 'about'       => 'pages#about'
  match 'user/new'    => 'user#new'
  match 'user/create' => 'user#create'
  match 'game/index'  => 'game#index'
  match 'user/create' => 'user#create'
  match 'game_create' => 'game#create'
  match 'games_show'   => 'game#show'
  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Facebooker2::Rails::Controller
  helper :all
  #protect_from_forgery
  

private

def fb_permission_check
	begin
		current_facebook_user.fetch
		if session[:user_name] == current_facebook_user.name

		else
		redirect_to '/user/new'
		end
	rescue
		render 'pages/fb_permission'
	end	
end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
	require 'mogli'

  def index
  	size = Like.count
		@like1 = Like.find(1+rand(size-1))
		@like2 = Like.find(1+rand(size-1))
		if @like1 == @like2
			@like2 = Like.find(1+rand(size-1))
		end

    @likes = Like.where("count != 0").order("count DESC")
  end

  def new
  end

  def show

    #@user_likes

  end 

  def create

    current_facebook_user.fetch
  	Game.create(:chosen => params[:chosen],
  				:not_chosen => params[:unchosen],
          :user_name => current_facebook_user.name)

  	@like = Like.find_by_group(params[:chosen])
  	@like.count +=1
  	if @like.save
  		redirect_to '/game/index'
  	end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_filter 'fb_permission_check'

  
  def index
  	

  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	require 'mogli'
	def new
	begin current_facebook_user.fetch
		if User.find_by_name(current_facebook_user.name) != nil
			session[:user_name] = User.find_by_name(current_facebook_user.name).name
			redirect_to root_path
		else
			@user = User.create(:name => current_facebook_user.name,
								:gender => current_facebook_user.gender,
								:birthday => current_facebook_user.birthday,
								:email => current_facebook_user.email)
			cookies.permanent[:user_name] = @user.name
			session[:user_name] = @user.name
			redirect_to '/user/create'
		end
	rescue
	print "Fehler" 
	end
	end

	def create
		current_facebook_user.fetch
		current_facebook_user.likes.each do |item|
			if Like.find_by_group(item.name)
			else
			Like.create(:group => item.name,
						:count => "0")	
			end
		end
		redirect_to root_path

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/game/create.html.erb
<h1>Game#create</h1>
<p>Find me in app/views/game/create.html.erb</p>

app/views/game/index.html.erb
<h1>dateGame</h1>

	<% link_to @like1.group, game_create_path(:chosen => @like1.group, :unchosen => @like2.group) %> << >>
	<% link_to @like2.group, game_create_path(:chosen => @like2.group, :unchosen => @like1.group) %> <br/>
	<% link_to "Skip", '/game/index' %>
	


	



-----------------------------------------------------------------------------------------------------------
<table>
<% @likes.each do |like| %>
<tr>
<td><%= like.group %></td>
<td><%= like.count %></td>
</tr>
<% end %>

</table>

app/views/game/new.html.erb
<h1>Game#new</h1>
<p>Find me in app/views/game/new.html.erb</p>

app/views/game/show.html.erb
<h1>Deine Interessen: </h1>

app/views/layouts/_navitop.html.erb
<div id = 'nav_top_area'>
  <ul>
      <li><div id='title'><%= link_to "dategame", root_path %></div></li>
      <li> | </li>
      <li><%= link_to "Spielen", '/game/index' %></li>
      <li> | </li>
      <li><%= link_to "Meine Interessen", games_show_path %></li>
  </ul>
</div>





app/views/layouts/_profile_left.html.erb


		<p>
		<h1><i>my Profile </i></h1>
			<% if session[:user_name] %>
				<% current_facebook_user.fetch %>
				<%= current_facebook_user.name %><br/>
				<%= current_facebook_user.email %><br/>
				<%= current_facebook_user.gender %><br/>
				<%= current_facebook_user.birthday %>
				
		</p>
		<p>
	
	<div id = "profilepic">
				<%= image_tag("http://graph.facebook.com/#{current_facebook_user.id}/picture", :size=> "80x80")%>
			<% end %>
		</p>
	</div>

	Games Played: 
	<% current_facebook_user.fetch %>
	<% @played_games = Game.where(:user_name => current_facebook_user.name).all %>
	<% if @played_games != nil %>
	<%= @played_games.count %>
	<% else %>
	<%= 0 %>
	<% end %>
	<br/>

	<%= link_to "Aktualisiere deine Interessen!", '/user/create' %>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoftwareProject</title>
  <%= stylesheet_link_tag 'application' %>


 
</head>
<body>
<div class ="container">
<%= render 'layouts/navitop' %>
</div>
<div class="container-fluid">
	<div class="sidebar">
		<%= render 'layouts/profile_left' %>
	</div>
	<div class = "content">
		<%= yield %>
	</div>
</div>	
	

</body>
</html>

app/views/pages/about.html.erb
<div id = 'content_pages'>
<h1>About</h1>

<%= link_to "back", root_path%>
</div>

app/views/pages/fb_permission.html.erb
<script>
		(function (){
    		window.top.location.href = 'https://www.facebook.com/dialog/oauth?client_id=280822525282026&redirect_uri=http://apps.facebook.com/testestestapp/user/new&scope=user_about_me,user_location,user_likes,user_interests,user_hometown,user_groups,friends_groups,friends_hometown,friends_interests,friends_likes,friends_location,email,user_birthday,friends_birthday';
		}());
	</script>